---
title: "Homework 6"
author: "Stefan Konigorski"
date: "December 2, 2021"
output:
  html_document: default
---

Download this R Markdown file, save it on your computer, and perform all the below tasks by inserting your answer in text or by inserting R chunks below. After you are done, upload this file with your solutions on Moodle.

## Exercise 1: Statistical tests

a) In the KiGGS dataset, perform a 2-sample t-test for paired samples (i.e. dependent samples) for the two variables 'sys1' and 'sys2'. Interpret the results.
b) In the KiGGS dataset, select one metric and one binary variable (or create one) and perform a 2-sample t-test. Then do a Mann-Whitney U-test with the same variables, explore the function to do this, and compare the results to the t-test.

## Exercise 2: Study planning (optional)

Compute the sample size using R or G*Power, for a study that investigates the question if biking to the HPI is associated with concentration in class or not.

Think about how you can formulate this study question in terms of variables, and which statistical test (that we have covered in class 6) would be appropriate for this.

a) Which test could you use?

b) Which sample size is necessary, to find a true effect with 80\% power at $\alpha=0.05$ using this statistical test?
